service: zip-downloadable

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.donwload
    events:
      - http:
          path: /download
          method: post
          cors: true